# Site/SEO settings
email: br.apps@icloud.com
baseurl: ""
permalink: /:year/:month/:day/:title/
# Link to your fathom analytics dashboard without http(s):// prepended
fathom_analytics_dashboard: brme-fathom-analytics.herokuapp.com
fathom_analytics_site_id: VEQHR

name: Bruce Roettgers
title: Bruce Roettgers
description: >
  This is my personal blog on my journey as a teen indie maker.
url: https://bruceroettgers.me
twitter_username: bcye_tw
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/bcye_tw
  - name: instagram
    url: https://www.instagram.com/bruce.roet/
  - name: github
    url: https://github.com/bcye

# Disqus settings
disqus: brme

# Buttondown settings
buttondown_id: bruceroet

# Author settings
author:
  - name: Bruce Roettgers
    bio: Hi, I'm the maker of this page, and am blogging about my journey as an indie maker.
    url: https://bruceroettgers.me

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
